AMB-863 Fix try this API feature
NHSDigital/booking-and-referral-fhir-api pull request #46
Opened 2021-10-29 08:21 UTC by RyanThomas1214

## Summary
* Routine Change
* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change

Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2021-11-01 14:20 UTC, SachinPath requested changes

2021-11-01 14:20 UTC, SachinPath commented on specification/booking-and-referral.yaml
> +    This API can only be used where there is a legal basis to do so. Make sure you have a valid use case before you go too far with your development. You must do this before you can go live (see ‘Onb
Has onboarding started for this API? I cannot see the "Onboarding" section in the overview section?  
If not then remove the (see ‘Onboarding’ below).

2021-11-01 14:20 UTC, SachinPath commented on specification/booking-and-referral.yaml
> +    This API uses HTTP POST to submit data.
See my comment on "This API is synchronous."

See [PDS FHIR API - Technology](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir#api-description__technology) section.

2021-11-01 14:20 UTC, SachinPath commented on specification/booking-and-referral.yaml
> +    ### Application-restricted access
Do we have more than one access mode for this API?

If not, remove the header for "Application-restricted access"

2021-11-01 14:20 UTC, SachinPath commented on specification/booking-and-referral.yaml
> +    This access mode is [application-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis),
If there is only one access mode, change to "This API is [application-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis),......."

2021-11-01 14:20 UTC, SachinPath commented on specification/booking-and-referral.yaml
> +
Does this API provide any data quality reports? 

I think the bullet point is applicable to the "[Ambulance data submission API.](https://digital.nhs.uk/developer/api-catalogue/ambulance-data-submission-fhir#api-description__security-and-authorisation)" 

Mention relevant benefits for the Integration environment of BaRS API.

2021-11-03 09:12 UTC, Valentinolucas approved these changes

2021-11-03 09:16 UTC, merged